In [1]:
import pandas as pd

df = pd.read_csv("/kaggle/input/datasets/redwankarimsony/heart-disease-data/heart_disease_uci.csv")
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0


**WEEK1** 

1. Build a Simple Neural Network with PyTorch1. 

In [2]:
import torch
import torch.nn as nn

# Step 1: Define Neural Network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        
        self.fc1 = nn.Linear(3, 5)   # input → hidden
        self.fc2 = nn.Linear(5, 1)   # hidden → output
        
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.sigmoid(self.fc2(x))
        return x

# Step 2: Create model
model = SimpleNN()

# Step 3: Dummy input (3 features)
x = torch.tensor([[0.5, 0.2, 0.1]])

# Step 4: Forward pass
output = model(x)

print("Output:", output)

Output: tensor([[0.5434]], grad_fn=<SigmoidBackward0>)


observation
* The neural network successfully generated an output for the given input using a forward pass.
* The output value changes each time due to randomly initialized weights.

Build a Simple Neural Network using TensorFlow

In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Step 1: Create model
model = keras.Sequential([
    layers.Dense(5, activation='relu', input_shape=(3,)),  # input → hidden
    layers.Dense(1, activation='sigmoid')                  # hidden → output
])

# Step 2: Dummy input
x = tf.constant([[0.5, 0.2, 0.1]])

# Step 3: Forward pass
output = model(x)

print("Output:", output)

2026-04-12 03:31:48.779354: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1775964708.998552      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1775964709.059937      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1775964709.586126      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775964709.586166      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775964709.586169      55 computation_placer.cc:177] computation placer alr

Output: tf.Tensor([[0.52996]], shape=(1, 1), dtype=float32)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-04-12 03:32:14.559430: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


Observations
* The TensorFlow model successfully produces an output using a simple neural network.
* The output varies due to random initialization of weights.

Build a Simple Neural Network using Keras (tf.keras)

In [5]:
from tensorflow import keras
from tensorflow.keras import layers

# Step 1: Create model
model = keras.Sequential([
    keras.Input(shape=(3,)),
    layers.Dense(5, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

# Step 2: Dummy input
import tensorflow as tf
x = tf.constant([[0.5, 0.2, 0.1]])

# Step 3: Forward pass
output = model(x)

print("Output:", output)

Output: tf.Tensor([[0.547079]], shape=(1, 1), dtype=float32)


Observations

* The Keras model successfully generates an output using a simple neural network.
* The output changes due to random initialization of weights.

Implement a Simple Perceptron

In [6]:
import numpy as np

# Step function
def step_function(x):
    return 1 if x >= 0 else 0

# Inputs and weights
inputs = np.array([1, 0])
weights = np.array([0.5, 0.5])
bias = -0.3

# Weighted sum
sum = np.dot(inputs, weights) + bias

# Output
output = step_function(sum)

print("Output:", output)

Output: 1


Observations
* The output of the perceptron changes based on the value of weights and bias.
* Increasing the bias makes it harder for the neuron to activate (output = 1), while decreasing the bias makes activation easier

**WEEK 2**

Implement AND & OR using a single perceptron + verify using truth table

In [7]:
import numpy as np

def step(x):
    return 1 if x >= 0 else 0

# AND gate
inputs = [(0,0), (0,1), (1,0), (1,1)]
weights = np.array([1, 1])
bias = -1.5

print("AND Gate:")
for x in inputs:
    sum = np.dot(x, weights) + bias
    print(x, "->", step(sum))

AND Gate:
(0, 0) -> 0
(0, 1) -> 0
(1, 0) -> 0
(1, 1) -> 1


In [9]:
# OR gate
weights = np.array([1, 1])
bias = -0.5

print("\nOR Gate:")
for x in inputs:
    sum = np.dot(x, weights) + bias
    print(x, "->", step(sum))


OR Gate:
(0, 0) -> 0
(0, 1) -> 1
(1, 0) -> 1
(1, 1) -> 1


Observations
* The perceptron correctly implements AND and OR logic by adjusting weights and bias values.
* Different bias values shift the decision boundary, enabling correct classification for each logic gate.

Examine the feasibility of implementing the XOR and XNOR (¬XOR) operations (Non linear data) using a single perceptron

In [10]:
import numpy as np

def step(x):
    return 1 if x >= 0 else 0

# XOR inputs
inputs = [(0,0), (0,1), (1,0), (1,1)]

# Try some weights & bias
weights = np.array([1, 1])
bias = -1

print("XOR Attempt:")
for x in inputs:
    sum = np.dot(x, weights) + bias
    print(x, "->", step(sum))

XOR Attempt:
(0, 0) -> 0
(0, 1) -> 1
(1, 0) -> 1
(1, 1) -> 1


In [11]:
import numpy as np

def step(x):
    return 1 if x >= 0 else 0

# XNOR inputs
inputs = [(0,0), (0,1), (1,0), (1,1)]

# Try weights & bias
weights = np.array([1, 1])
bias = -0.5

print("XNOR Attempt:")
for x in inputs:
    sum = np.dot(x, weights) + bias
    print(x, "->", step(sum))

XNOR Attempt:
(0, 0) -> 0
(0, 1) -> 1
(1, 0) -> 1
(1, 1) -> 1


Observations 
* A single perceptron fails to correctly implement both XOR and XNOR as their outputs do not match the expected truth tables.
* This is because both problems are non-linearly separable and cannot be solved using a single decision boundary

Implement the XOR and (¬XOR) logic operation using a multi-perceptron network

In [13]:
import numpy as np
from sklearn.neural_network import MLPClassifier

X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0, 1, 1, 0])

model = MLPClassifier(hidden_layer_sizes=(4,), activation='tanh', max_iter=5000)

model.fit(X, y)

print("Predictions:")
for i in X:
    print(i, "->", model.predict([i])[0])

Predictions:
[0 0] -> 0
[0 1] -> 1
[1 0] -> 1
[1 1] -> 0


Observation
* Initially, the model failed to learn XOR due to insufficient neurons and iterations.
* After adjusting hidden neurons and activation function, the MLP successfully learned the non-linear pattern.

implement the Perceptron Learning Algorithm and study the effect of weight updates on convergence for a binary decision problem

In [19]:
import numpy as np

# f1, f2, f3, f4 → output
X = np.array([
    [1, 1, 0, 0.8],
    [0, 1, 1, 0.6],
    [1, 0, 0, 0.2],
    [0, 0, 1, 0.3]
])

y = np.array([1, 1, 0, 0])

i) MP Perceptron (NO weights, NO bias)

In [21]:
def mp_perceptron(x):
    return 1 if np.sum(x) >= 2 else 0

print("MP Perceptron:")
for i in X:
    print(i, "->", mp_perceptron(i))

MP Perceptron:
[1.  1.  0.  0.8] -> 1
[0.  1.  1.  0.6] -> 1
[1.  0.  0.  0.2] -> 0
[0.  0.  1.  0.3] -> 0


ii) Perceptron (WITH weights, NO bias)

In [22]:
weights = np.zeros(4)
lr = 0.1

def step(x):
    return 1 if x >= 0 else 0

# Training
for _ in range(10):
    for i in range(len(X)):
        y_pred = step(np.dot(X[i], weights))
        error = y[i] - y_pred
        weights += lr * error * X[i]

print("\nWeights:", weights)

# Testing
print("Perceptron (no bias):")
for i in X:
    print(i, "->", step(np.dot(i, weights)))


Weights: [-0.1   0.1  -0.1   0.01]
Perceptron (no bias):
[1.  1.  0.  0.8] -> 1
[0.  1.  1.  0.6] -> 1
[1.  0.  0.  0.2] -> 0
[0.  0.  1.  0.3] -> 0


iii) Perceptron (WITH weights + bias)

In [23]:
weights = np.zeros(4)
bias = 0
lr = 0.1

# Training
for _ in range(10):
    for i in range(len(X)):
        y_pred = step(np.dot(X[i], weights) + bias)
        error = y[i] - y_pred
        weights += lr * error * X[i]
        bias += lr * error

print("\nWeights:", weights, "Bias:", bias)

# Testing
print("Perceptron (with bias):")
for i in X:
    print(i, "->", step(np.dot(i, weights) + bias))


Weights: [-0.1  0.2  0.   0.1] Bias: -0.1
Perceptron (with bias):
[1.  1.  0.  0.8] -> 1
[0.  1.  1.  0.6] -> 1
[1.  0.  0.  0.2] -> 0
[0.  0.  1.  0.3] -> 0


Observations
* Weight updates help the perceptron learn from errors and improve classification over iterations.
* The model performs best when both weights and bias are used, as it allows flexible decision boundaries

Design and implement a Multi-Layer Perceptron (MLP) architecture capable of realizing all basic Boolean functions 

In [26]:
import numpy as np

def step(x):
    return 1 if x > 0 else 0   # strict >

def hidden_layer(x1, x2):
    h1 = step(0.5 - x1 - x2)        # (0,0)
    h2 = step(x2 - x1 - 0.5)        # (0,1)
    h3 = step(x1 - x2 - 0.5)        # (1,0)
    h4 = step(x1 + x2 - 1.5)        # (1,1)
    return np.array([h1, h2, h3, h4])

def output_layer(h):
    weights = np.array([0, 1, 1, 0])  # XOR
    return step(np.dot(h, weights) - 0.5)

inputs = [(0,0), (0,1), (1,0), (1,1)]

for x1, x2 in inputs:
    h = hidden_layer(x1, x2)
    y = output_layer(h)
    print((x1, x2), "->", y)

(0, 0) -> 0
(0, 1) -> 1
(1, 0) -> 1
(1, 1) -> 0


How many Boolean functions can be designed using three binary inputs?

In [27]:
import numpy as np

def mlp(x):
    # hidden layer (one-hot)
    h = [
        int(x == (0,0,0)),
        int(x == (0,0,1)),
        int(x == (0,1,0)),
        int(x == (0,1,1)),
        int(x == (1,0,0)),
        int(x == (1,0,1)),
        int(x == (1,1,0)),
        int(x == (1,1,1))
    ]
    
    weights = [0,0,0,0,0,0,0,1]  # example function
    
    return 1 if np.dot(h, weights) >= 1 else 0

inputs = [
    (0,0,0),(0,0,1),(0,1,0),(0,1,1),
    (1,0,0),(1,0,1),(1,1,0),(1,1,1)
]

for i in inputs:
    print(i, "->", mlp(i))

(0, 0, 0) -> 0
(0, 0, 1) -> 0
(0, 1, 0) -> 0
(0, 1, 1) -> 0
(1, 0, 0) -> 0
(1, 0, 1) -> 0
(1, 1, 0) -> 0
(1, 1, 1) -> 1
